"""Chat with the distilled comfort-kin persona.

- Loads a persona profile JSON generated by distill_persona.py
- Provides a lightweight interactive CLI chat

This is meant to be the simplest 'directly runnable' entrypoint.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from openai import OpenAI

from utils import PROFILES_DIR, load_json


def build_system(profile: dict) -> str:
    relationship = profile.get("relationship", "亲人")
    calls_user = profile.get("calls_user", "")
    tone = ", ".join(profile.get("tone_keywords", [])[:10])
    catchphrases = "；".join(profile.get("catchphrases", [])[:12])
    dos = "；".join(profile.get("dos", [])[:12])
    donts = "；".join(profile.get("donts", [])[:12])
    comfort = "\n".join([f"- {x}" for x in profile.get("comfort_templates", [])[:8]])
    topics = "；".join(profile.get("small_talk_topics", [])[:12])
    signature = profile.get("signature", "")

    return f"""你在扮演用户的{relationship}，与用户长期陪伴聊天。

**核心风格**
- 你称呼用户：{calls_user or '（按语境自然称呼，如“你/宝宝/孩子/小名”）'}
- 语气关键词：{tone or '温柔、耐心、少说教'}
- 常用语/口头禅：{catchphrases or '（缺失时少量使用自然口语）'}

**你应该做（dos）**
{dos or '（缺失时：多关心感受、少评判、给小建议）'}

**你不要做（donts）**
{donts or '（缺失时：不要命令/训斥，不要长篇大道理）'}

**安慰/鼓励模板（优先复用/改写）**
{comfort or '- （缺失时：先共情，再给一个小步骤建议）'}

**适合的小话题**
{topics or '（缺失时：吃饭睡觉、工作学习、天气、身体、心情）'}

**签名/收尾习惯**
{signature or '（缺失时：用一句温柔的收尾，比如“有我在呢”）'}

要求：
- 用中文回复。
- 回复长度默认 2-6 句，除非用户要求细讲。
- 优先共情与陪伴，给建议要轻、短、可执行。
"""


def main() -> None:
    ap = argparse.ArgumentParser(description="Chat with comfort-kin companion persona")
    ap.add_argument("--profile", default="default", help="Profile name or path to JSON")
    args = ap.parse_args()

    profile_arg = args.profile
    if profile_arg.endswith(".json"):
        profile_path = Path(profile_arg).expanduser().resolve()
    else:
        profile_path = PROFILES_DIR / f"{profile_arg}.json"

    if not profile_path.exists():
        raise FileNotFoundError(
            f"Profile not found: {profile_path}. Run distill_persona.py first."
        )

    profile = load_json(profile_path)

    client = OpenAI()
    system = build_system(profile)

    messages = [{"role": "system", "content": system}]

    print("亲人陪伴已上线。输入 /exit 退出，/reset 清空对话。\n")
    while True:
        try:
            user_inp = input("你：").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n再见。")
            return

        if not user_inp:
            continue
        if user_inp in {"/exit", "/quit"}:
            print("再见。")
            return
        if user_inp == "/reset":
            messages = [{"role": "system", "content": system}]
            print("（已清空对话）")
            continue

        messages.append({"role": "user", "content": user_inp})

        resp = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-4.1-mini"),
            temperature=0.7,
            messages=messages,
        )
        ans = resp.choices[0].message.content.strip()
        messages.append({"role": "assistant", "content": ans})
        print(f"亲人：{ans}\n")


if __name__ == "__main__":
    main()
